### ISSUE TITLE
SyntaxError on empty `.mdastrc`

### ISSUE THREAD

**Issue by wooorm** [leipert/linter-markdown#1]
Alright... here come some issues 😉

I just created a new directory with `test.md` and `.mdastrc` (both empty), and got the attached error. Albeit this is handled pretty great already, maybe a prettier error should be thrown?

![screen shot 2015-08-04 at 10 22 59 a m](https://cloud.githubusercontent.com/assets/944406/9056358/cf679fb6-3a92-11e5-9b84-eca37b6302ad.png)

**Comment by leipert** [comment]
Catching the error now:
![](http://g.recordit.co/kMrNoIibSo.gif)
