### ISSUE TITLE
Add support for reloading `.mdastrc` config

### ISSUE THREAD

**Issue by wooorm** [leipert/linter-markdown#3]
Currently, I have to close and re-open the project in Atom for setting changes to take affect.

I think this has to do with [`new Configuration`](https://github.com/leipert/linter-markdown/blob/master/lib/linter.coffee#L18) being outside of the [`lint`](https://github.com/leipert/linter-markdown/blob/master/lib/linter.coffee#L28) scope.

**Comment by leipert** [comment]
Sorry. I did not see the issues, as I was not watching the repository :dancer: 

You can see it working without reopening atom below:

![](http://g.recordit.co/kMrNoIibSo.gif)

**Comment by wooorm** [comment]
Very nice work! Very useful! :+1:
