### ISSUE TITLE
Replace tilde (`~`) with caret (`^`) for mdast, mdast-lint

### ISSUE THREAD

**Issue by wooorm** [leipert/linter-markdown#4]
I follow SemVer on those, so only non-breaking features are included on minor and patch releases (which the caret catches, but the tilde only catches patch releases).

Yesterday I added support for multiple disables (`<!--lint disable no-html first-heading-level-->`), but now I have to wait for a new `linter-markdown` release to get access to them!

**Comment by leipert** [comment]
I do not know how atom handles updates of dependencies, once there are improvements on mdast and mdast-lint, I want to publish a new version, so that all users can experience the new features.

I will add a watch to mdast and mdast-lint, so every time you upgrade, I will follow within a day or two.

**Comment by wooorm** [comment]
Oh that's great. Yeah you would still need to uninstall and reinstall to get the updates.
Anyway, thanks a lot!

**Comment by wooorm** [comment]
@leipert You can close this btw if you’d like :smile:
